name: nginx-test

commands:
  server:
    run: |
      docker run  --name nginx-test \
                  --rm \
                  -p 8080:80 \
                  -v ${PWD}/etc/nginx/nginx.conf:/etc/nginx/nginx.conf \
                  -v ${PWD}/etc/nginx/conf.d:/etc/nginx/conf.d \
                  -v ${PWD}/usr/share/nginx/html:/usr/share/nginx/html \
                  nginx
